// Define sensor types for the system
// Maximum value is 0x7F

#define SENSOR_ALTIMETER 0x01

// Define temperature sensor types
#define SENSOR_TEMPERATURE 0x10
#define SENSOR_TEMPERATURE_CHT 0x11
#define SENSOR_TEMPERATURE_CHT_1 0x12
#define SENSOR_TEMPERATURE_CHT_2 0x13
#define SENSOR_TEMPERATURE_CHT_3 0x14
#define SENSOR_TEMPERATURE_CHT_4 0x15
#define SENSOR_TEMPERATURE_CHT_5 0x16
#define SENSOR_TEMPERATURE_CHT_6 0x17
#define SENSOR_TEMPERATURE_AMB 0x18
#define SENSOR_TEMPERATURE_INTAKE 0x19
#define SENSOR_TEMPERATURE_COCKPIT 0x1A

#define SENSOR_TEMPERATURE_EGT 0x20
#define SENSOR_TEMPERATURE_EGT_1 0x21
#define SENSOR_TEMPERATURE_EGT_2 0x22
#define SENSOR_TEMPERATURE_EGT_3 0x23
#define SENSOR_TEMPERATURE_EGT_4 0x24
#define SENSOR_TEMPERATURE_END 0x25
