// Define sensor types for the system
// Maximum value is 0x7F

#ifndef SENSOR_TYPES_H
#define SENSOR_TYPES_H

#define SENSOR_ALTIMETER 0x01

// Define temperature sensor types
#define SENSOR_TEMPERATURE 0x10
#define SENSOR_TEMPERATURE_CHT 0x11
#define SENSOR_TEMPERATURE_CHT_1 0x12
#define SENSOR_TEMPERATURE_CHT_2 0x13
#define SENSOR_TEMPERATURE_CHT_3 0x14
#define SENSOR_TEMPERATURE_CHT_4 0x15
#define SENSOR_TEMPERATURE_CHT_5 0x16
#define SENSOR_TEMPERATURE_CHT_6 0x17
#define SENSOR_TEMPERATURE_AMB 0x18
#define SENSOR_TEMPERATURE_INTAKE 0x19
#define SENSOR_TEMPERATURE_COCKPIT 0x1A
#define SENSOR_TEMPERATURE_OIL 0x1B
#define SENSOR_TEMPERATURE_WATER 0x1C

#define SENSOR_TEMPERATURE_EGT 0x20
#define SENSOR_TEMPERATURE_EGT_1 0x21
#define SENSOR_TEMPERATURE_EGT_2 0x22
#define SENSOR_TEMPERATURE_EGT_3 0x23
#define SENSOR_TEMPERATURE_EGT_4 0x24

// Define pressure sensor types
#define SENSOR_PRESSURE_OIL 0x30
#define SENSOR_PRESSURE_FUEL 0x31
#define SENSOR_PRESSURE_MANIFOLD 0x32

// Define fuel sensor types
#define SENSOR_FUEL_LEVEL 0x40
#define SENSOR_FUEL_FLOW 0x41
#define SENSOR_FUEL_PRESSURE 0x42

// Define electrical sensor types
#define SENSOR_BATTERY_VOLTAGE 0x50
#define SENSOR_BATTERY_CURRENT 0x51

// Define navigation sensor types
#define SENSOR_MAGNETIC_HEADING 0x60
#define SENSOR_GPS_SPEED 0x61
#define SENSOR_GPS_ALTITUDE 0x62
#define SENSOR_GPS_LATITUDE 0x63
#define SENSOR_GPS_LONGITUDE 0x64
#define SENSOR_GPS_SATELLITES 0x65

#endif // SENSOR_TYPES_H
