; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

[env:canbusMonitor]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
    SPI
    Wire @ ^1.0
    watterott/MCP2515@^1.0.0
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    adafruit/RTClib@^2.1.1
    SD

[env:canbusMonitorSimulator]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_flags = -DBUILD_SIMULATOR
lib_deps =
    SPI
    Wire @ ^1.0
    watterott/MCP2515@^1.0.0
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    adafruit/RTClib@^2.1.1
    SD
