; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

[env:canMock]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5
extra_scripts = pre:increment_build.py
lib_deps =
    SPI
    coryjfowler/mcp_can@^1.5.0
