; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

[env:canbusLogger]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5
extra_scripts = pre:increment_build.py
lib_deps =
    SPI
    Wire @ ^1.0
    watterott/MCP2515@^1.0.0
    adafruit/RTClib@^2.1.1
    SD
