; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

[env:basicFlightInstruments]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5
extra_scripts = pre:increment_build.py
lib_deps =
    SPI
    Wire @ ^1.0
    coryjfowler/mcp_can@^1.5.0
    adafruit/Adafruit BMP085 Library@^1.2.2
